export const CLEAR_STATE = "CLEAR_STATE";
//loading
export const AUTH_SET_LOADING = "AUTH_SET_LOADING";
//login registartion
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";
//notifier
export const SET_NOTIFIER = "SET_NOTIFIER";
//user
export const USER_SET_LOADING = "USER_SET_LOADING";
export const USER_FETCHED_GET_CONTACTS = "USER_FETCHED_GET_CONTACTS";
export const USER_GET_CONTACTS_FAIL = "USER_FETCHED_GET_CONTACTS_FAIL";
export const USER_GET_CONTACTS_SUCCESS = "USER_GET_CONTACTS_SUCCESS";
//create contact
export const CREATE_CONTACT_FETCHED = "CREATE_CONTACT_FETCHED";
export const CREATE_CONTACT_SET_LOADING = "CREATE_CONTACT_SET_LOADING";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";
//edite contact
export const EDIT_GET_CONTACT_SUCCESS = "EDIT_GET_CONTACT_SUCCESS";
export const EDIT_CONTACT_FETCHED = "EDIT_CONTACT_FETCHED";
export const EDIT_CONTACT_SET_LOADING = "EDIT_CONTACT_SET_LOADING";
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
export const EDIT_CONTACT_FAIL = "EDIT_CONTACT_FAIL";
export const EDIT_CONTACT_DELETE_SUCCESS = "EDIT_CONTACT_DELETE_SUCCESS";
